name: Deploy to Server

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server via rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude=.git --exclude=.github
        path: ./
        remote_path: www/jelezo.by/TEST/
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}  # или используйте remote_password
        remote_port: ${{ secrets.SERVER_PORT }}